language: rust
sudo: false

matrix:
  include:
    - name: Rustfmt
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/doc/
  on:
    branch: master
