language: rust
sudo: false

matrix:
  include:
    - name: Build
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo build --verbose
        - cargo test --verbose
        - cargo doc --verbose

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/doc/
  on:
    branch: master
