[package]
name = "psutil"
version = "0.8.0"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "Process monitoring library"
repository = "https://github.com/borntyping/rust-psutil"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.1.2"

[dev-dependencies]
tempdir = "*"
