[package]
name = "psutil"
version = "1.7.0"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "Process monitoring library"
repository = "https://github.com/borntyping/rust-psutil"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
libc = { version = "0.2.66" }
once_cell = { version = "1.2.0" }

num_cpus = { version = "1.11.1", optional = true }
platforms = { version = "0.2.1", optional = true }
snafu = { version = "0.6.0", optional = true }
signal = { version = "0.7.0", optional = true }

[features]
default = ["cpu", "disk", "host", "memory", "network", "process", "sensors"]

# Modules
cpu = ["num_cpus"]
disk = []
host = ["platforms"]
memory = []
network = []
process = ["snafu", "signal"]
sensors = []

[dev-dependencies]
float-cmp = "0.6.0"
