[package]
name = "psutil"
version = "1.0.0"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "Process monitoring library"
repository = "https://github.com/borntyping/rust-psutil"
readme = "README.md"
license = "MIT"

[dependencies]
libc = ">= 0.1.4"
lazy_static = "0.1"

[dev-dependencies]
tempdir = "*"
