[package]
name = "psutil"
version = "1.8.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>", "Rob Day <rkd@rkd.me.uk>", "Sam Clements <sam@borntyping.co.uk>"]
description = "Process monitoring library"
repository = "https://github.com/rust-psutil/rust-psutil"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
libc = ">= 0.1.4"
lazy_static = "1"
